import type { Listing, Valuation, Deal, DealTimelineEvent, Lender, DealStage, Message } from '@/types'

export const LENDERS: Lender[] = [
  { id: 'bmw_fs', name: 'BMW Financial Services' },
  { id: 'volkswagen_fs', name: 'Volkswagen Financial Services' },
  { id: 'mercedes_fs', name: 'Mercedes-Benz Financial Services' },
  { id: 'black_horse', name: 'Black Horse (Lloyds)' },
  { id: 'santander_consumer', name: 'Santander Consumer Finance' },
  { id: 'motonovo', name: 'MotoNovo Finance' },
  { id: 'close_brothers', name: 'Close Brothers Motor Finance' },
  { id: 'alphera', name: 'Alphera Financial Services' },
]

// Named valuations for demo regs
const VALUATIONS: Record<string, Valuation> = {
  'LR21KXM': {
    reg: 'LR21 KXM',
    year: 2021,
    make: 'Land Rover',
    model: 'Defender',
    trim: '110 S D200',
    colour: 'Gondwana Stone',
    mileage: 28400,
    dealerOffer: 41200,
    privateViaHandover: 44500,
    estimatedLow: 42000,
    estimatedHigh: 46000,
    outstandingFinance: 31500,
    lender: 'Black Horse (Lloyds)',
    financeType: 'pcp',
  },
  'MA22FGH': {
    reg: 'MA22 FGH',
    year: 2022,
    make: 'BMW',
    model: 'M340i',
    trim: 'xDrive Touring M Sport',
    colour: 'Brooklyn Grey',
    mileage: 19200,
    dealerOffer: 33800,
    privateViaHandover: 36500,
    estimatedLow: 35000,
    estimatedHigh: 38000,
    outstandingFinance: 22150,
    lender: 'BMW Financial Services',
    financeType: 'pcp',
  },
  'YC20PWE': {
    reg: 'YC20 PWE',
    year: 2020,
    make: 'Porsche',
    model: 'Macan',
    trim: 'S PDK',
    colour: 'Miami Blue',
    mileage: 34100,
    dealerOffer: 36900,
    privateViaHandover: 39800,
    estimatedLow: 37500,
    estimatedHigh: 41000,
    outstandingFinance: 28200,
    lender: 'Volkswagen Financial Services',
    financeType: 'hp',
  },
}

// Generic fallback that hashes a reg into a believable VW Golf valuation
function hashReg(reg: string): number {
  let h = 0
  for (let i = 0; i < reg.length; i++) {
    h = (h * 31 + reg.charCodeAt(i)) >>> 0
  }
  return h
}

export function getValuation(reg: string): Valuation {
  const clean = reg.replace(/\s/g, '').toUpperCase()
  if (VALUATIONS[clean]) return VALUATIONS[clean]
  const h = hashReg(clean)
  const mileage = 18000 + (h % 30000)
  const dealerOffer = 14800 + (h % 8000)
  const premium = 1800 + (h % 1200)
  return {
    reg: clean.slice(0, 4) + ' ' + clean.slice(4),
    year: 2019 + (h % 4),
    make: 'Volkswagen',
    model: 'Golf',
    trim: ['Match', 'Life', 'R-Line', 'GTI'][h % 4],
    colour: ['Indium Grey', 'Pure White', 'Deep Black', 'Reef Blue'][h % 4],
    mileage,
    dealerOffer,
    privateViaHandover: dealerOffer + premium,
    estimatedLow: dealerOffer + 400,
    estimatedHigh: dealerOffer + premium + 600,
    outstandingFinance: dealerOffer - 4000 + (h % 3000),
    lender: LENDERS[h % LENDERS.length].name,
    financeType: ['pcp', 'hp', 'pcp'][h % 3] as 'pcp' | 'hp',
  }
}

// Mock API delay
export async function delay(ms = 700): Promise<void> {
  return new Promise(r => setTimeout(r, ms))
}

export const LISTINGS: Listing[] = [
  {
    id: 'lst_001',
    reg: 'MA22 FGH',
    year: 2022,
    make: 'BMW',
    model: 'M340i',
    trim: 'xDrive Touring M Sport',
    bodyType: 'estate',
    fuel: 'petrol',
    transmission: 'automatic',
    colour: 'Brooklyn Grey',
    mileage: 19200,
    askingPrice: 36500,
    dealerOffer: 33800,
    outstandingFinance: 22150,
    lender: 'BMW Financial Services',
    financeType: 'pcp',
    location: 'Edinburgh',
    description: 'Immaculate M340i Touring in the best colour combination. Full BMW dealer service history, original purchase receipts, and all keys. Towbar fitted. Currently on PCP with BMW FS — Handover will settle directly on completion. No Saturday-morning phone calls required.',
    photos: [
      'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?w=1200&q=85',
      'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=1200&q=85',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?w=800&q=85',
    viewCount: 247,
    saveCount: 18,
    daysListed: 3,
    sellerId: 'usr_james',
    sellerName: 'James',
    hpiClean: true,
    createdAt: '2026-05-05',
  },
  {
    id: 'lst_002',
    reg: 'LR21 KXM',
    year: 2021,
    make: 'Land Rover',
    model: 'Defender',
    trim: '110 S D200',
    bodyType: 'suv',
    fuel: 'diesel',
    transmission: 'automatic',
    colour: 'Gondwana Stone',
    mileage: 28400,
    askingPrice: 44500,
    dealerOffer: 41200,
    outstandingFinance: 31500,
    lender: 'Black Horse (Lloyds)',
    financeType: 'pcp',
    location: 'Bristol',
    description: 'Stunning Defender 110 in Gondwana Stone with black contrast roof. Upgraded with larger alloys and sliding pano roof. Used as a family car, no off-roading. Comes with original floor mats and all accessories. Finance settled directly by Handover on sale.',
    photos: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=85',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=85',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=85',
    viewCount: 389,
    saveCount: 31,
    daysListed: 5,
    sellerId: 'usr_sarah',
    sellerName: 'Sarah',
    hpiClean: true,
    createdAt: '2026-05-03',
  },
  {
    id: 'lst_003',
    reg: 'YC20 PWE',
    year: 2020,
    make: 'Porsche',
    model: 'Macan',
    trim: 'S PDK',
    bodyType: 'suv',
    fuel: 'petrol',
    transmission: 'automatic',
    colour: 'Miami Blue',
    mileage: 34100,
    askingPrice: 39800,
    dealerOffer: 36900,
    outstandingFinance: 28200,
    lender: 'Volkswagen Financial Services',
    financeType: 'hp',
    location: 'Manchester',
    description: 'Miami Blue Macan S — one of the most striking colour options on this generation. Sport Chrono package, panoramic sunroof, 20" Sport Classic wheels. Porsche Centre service history throughout. HP finance with VW FS, settled at completion.',
    photos: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85',
      'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=85',
    viewCount: 156,
    saveCount: 12,
    daysListed: 8,
    sellerId: 'usr_dan',
    sellerName: 'Dan',
    hpiClean: true,
    createdAt: '2026-04-30',
  },
  {
    id: 'lst_004',
    reg: 'HF71 TJW',
    year: 2021,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'AMG Line Premium',
    bodyType: 'saloon',
    fuel: 'petrol',
    transmission: 'automatic',
    colour: 'Selenite Grey',
    mileage: 22800,
    askingPrice: 31200,
    dealerOffer: 28900,
    outstandingFinance: 18500,
    lender: 'Mercedes-Benz Financial Services',
    financeType: 'pcp',
    location: 'London',
    description: 'Elegant C-Class AMG Line in Selenite Grey. Burmester sound, head-up display, 360 camera. Only ever serviced by Mercedes-Benz dealers. One careful owner, ULEZ compliant.',
    photos: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=85',
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=85',
    viewCount: 203,
    saveCount: 14,
    daysListed: 2,
    sellerId: 'usr_priya',
    sellerName: 'Priya',
    hpiClean: true,
    createdAt: '2026-05-06',
  },
  {
    id: 'lst_005',
    reg: 'KT22 XRL',
    year: 2022,
    make: 'Tesla',
    model: 'Model 3',
    trim: 'Long Range AWD',
    bodyType: 'saloon',
    fuel: 'electric',
    transmission: 'automatic',
    colour: 'Pearl White',
    mileage: 31500,
    askingPrice: 27800,
    dealerOffer: 24900,
    outstandingFinance: 19200,
    lender: 'Santander Consumer Finance',
    financeType: 'hp',
    location: 'Leeds',
    description: 'Long Range Model 3 with Enhanced Autopilot. White interior, glass roof. Only 31k miles, mostly motorway. Full-service history via Tesla Service. HP loan with Santander — Handover handles the settlement.',
    photos: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=85',
      'https://images.unsplash.com/photo-1569335245897-4c7ccdc2f82b?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=85',
    viewCount: 411,
    saveCount: 42,
    daysListed: 1,
    sellerId: 'usr_tom',
    sellerName: 'Tom',
    hpiClean: true,
    createdAt: '2026-05-07',
  },
  {
    id: 'lst_006',
    reg: 'SF70 PLN',
    year: 2020,
    make: 'Volkswagen',
    model: 'Golf',
    trim: 'GTI Performance',
    bodyType: 'hatchback',
    fuel: 'petrol',
    transmission: 'manual',
    colour: 'Tornado Red',
    mileage: 41200,
    askingPrice: 22500,
    dealerOffer: 19800,
    outstandingFinance: 11400,
    lender: 'Volkswagen Financial Services',
    financeType: 'pcp',
    location: 'Birmingham',
    description: 'Golf GTI Performance in Tornado Red with the Akrapovic exhaust option. Track-day friendly, daily driven. Comes with full VW service history and two sets of tyres (winter and summer). PCP with VW FS.',
    photos: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&q=85',
      'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=1200&q=85',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=85',
    viewCount: 178,
    saveCount: 19,
    daysListed: 11,
    sellerId: 'usr_luke',
    sellerName: 'Luke',
    hpiClean: true,
    createdAt: '2026-04-27',
  },
]

const TIMELINE_STAGES: { stage: DealStage; label: string }[] = [
  { stage: 'listed', label: 'Listed' },
  { stage: 'buyer_found', label: 'Buyer found' },
  { stage: 'funds_in_escrow', label: 'Funds in escrow' },
  { stage: 'lender_contacted', label: 'Lender contacted' },
  { stage: 'settlement_paid', label: 'Settlement paid' },
  { stage: 'v5c_transferred', label: 'V5C transferred' },
  { stage: 'pickup_arranged', label: 'Pickup arranged' },
  { stage: 'released', label: 'Released to buyer' },
]

function buildTimeline(currentStage: DealStage): DealTimelineEvent[] {
  const currentIdx = TIMELINE_STAGES.findIndex(s => s.stage === currentStage)
  return TIMELINE_STAGES.map((s, i) => ({
    stage: s.stage,
    label: s.label,
    completedAt: i < currentIdx ? `May ${i + 1}, 2026` : undefined,
    isCurrent: i === currentIdx,
  }))
}

export const DEALS: Deal[] = [
  {
    id: 'deal_001',
    listingId: 'lst_001',
    reg: 'MA22 FGH',
    carName: '2022 BMW M340i',
    buyerName: 'Alex Chen',
    sellerName: 'James T.',
    stage: 'lender_contacted',
    value: 36500,
    settlement: 22150,
    walkAway: 14251,
    updatedAt: '2026-05-08T09:14:00Z',
    timeline: buildTimeline('lender_contacted'),
  },
  {
    id: 'deal_002',
    listingId: 'lst_002',
    reg: 'LR21 KXM',
    carName: '2021 Land Rover Defender',
    buyerName: 'Sophie Williams',
    sellerName: 'Sarah M.',
    stage: 'funds_in_escrow',
    value: 44500,
    settlement: 31500,
    walkAway: 12901,
    updatedAt: '2026-05-08T08:30:00Z',
    timeline: buildTimeline('funds_in_escrow'),
  },
  {
    id: 'deal_003',
    listingId: 'lst_003',
    reg: 'YC20 PWE',
    carName: '2020 Porsche Macan S',
    buyerName: 'Matt Okafor',
    sellerName: 'Dan R.',
    stage: 'settlement_paid',
    value: 39800,
    settlement: 28200,
    walkAway: 11501,
    updatedAt: '2026-05-07T16:22:00Z',
    timeline: buildTimeline('settlement_paid'),
  },
  {
    id: 'deal_004',
    listingId: 'lst_004',
    reg: 'HF71 TJW',
    carName: '2021 Mercedes C-Class',
    buyerName: 'Raj Patel',
    sellerName: 'Priya S.',
    stage: 'buyer_found',
    value: 31200,
    settlement: 18500,
    walkAway: 12601,
    updatedAt: '2026-05-08T11:05:00Z',
    timeline: buildTimeline('buyer_found'),
  },
  {
    id: 'deal_005',
    listingId: 'lst_005',
    reg: 'KT22 XRL',
    carName: '2022 Tesla Model 3',
    buyerName: 'Fiona Clarke',
    sellerName: 'Tom H.',
    stage: 'v5c_transferred',
    value: 27800,
    settlement: 19200,
    walkAway: 8501,
    updatedAt: '2026-05-07T14:10:00Z',
    timeline: buildTimeline('v5c_transferred'),
  },
  {
    id: 'deal_006',
    listingId: 'lst_006',
    reg: 'SF70 PLN',
    carName: '2020 VW Golf GTI',
    buyerName: 'Callum Burns',
    sellerName: 'Luke P.',
    stage: 'released',
    value: 22500,
    settlement: 11400,
    walkAway: 11001,
    updatedAt: '2026-05-07T10:00:00Z',
    timeline: buildTimeline('released'),
  },
  {
    id: 'deal_007',
    listingId: 'lst_001',
    reg: 'WP21 KMZ',
    carName: '2021 Audi Q5 S Line',
    buyerName: 'Helena Fox',
    sellerName: 'Chris D.',
    stage: 'pickup_arranged',
    value: 34900,
    settlement: 24100,
    walkAway: 10701,
    updatedAt: '2026-05-07T18:40:00Z',
    timeline: buildTimeline('pickup_arranged'),
  },
  {
    id: 'deal_008',
    listingId: 'lst_002',
    reg: 'GN22 VHJ',
    carName: '2022 Range Rover Sport',
    buyerName: 'Oliver Nash',
    sellerName: 'Emma K.',
    stage: 'funds_in_escrow',
    value: 68000,
    settlement: 48500,
    walkAway: 19401,
    updatedAt: '2026-05-08T07:55:00Z',
    timeline: buildTimeline('funds_in_escrow'),
  },
]

export const DASHBOARD_MESSAGES: Message[] = [
  {
    id: 'msg_001',
    from: 'buyer',
    fromName: 'Alex Chen',
    text: "Hi James, I've transferred the funds into escrow. Has the Handover team been in touch with BMW yet?",
    sentAt: '2026-05-08T09:14:00Z',
  },
  {
    id: 'msg_002',
    from: 'seller',
    fromName: 'James',
    text: "Yes — I got an email this morning confirming they've contacted BMW Financial Services. Should be settled in 1–2 working days.",
    sentAt: '2026-05-08T09:31:00Z',
  },
  {
    id: 'msg_003',
    from: 'buyer',
    fromName: 'Alex Chen',
    text: "Perfect. I'm planning to collect Saturday morning — does that work for you?",
    sentAt: '2026-05-08T10:02:00Z',
  },
  {
    id: 'msg_004',
    from: 'seller',
    fromName: 'James',
    text: "Saturday at 10am works great. I'll have both keys and the V5C ready.",
    sentAt: '2026-05-08T10:18:00Z',
  },
]

export function getListingById(id: string): Listing | undefined {
  return LISTINGS.find(l => l.id === id)
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', maximumFractionDigits: 0 }).format(amount)
}

export function formatReg(reg: string): string {
  const clean = reg.replace(/\s/g, '').toUpperCase()
  if (clean.length >= 7) return clean.slice(0, 4) + ' ' + clean.slice(4)
  return clean
}
